;FFMETADATA1
TITLE=The Dragon Reborn
ARTIST=Robert Jordan
ALBUM=The Wheel of Time
GENRE=Audiobook

[CHAPTER]
TIMEBASE=1/1000
START=0
END=284125
TITLE=Chapter 0. Fortress of the Light

[CHAPTER]
TIMEBASE=1/1000
START=284125
END=369866
TITLE=Chapter 1. Waiting

[CHAPTER]
TIMEBASE=1/1000
START=369866
END=512015
TITLE=Chapter 2. Saidin

[CHAPTER]
TIMEBASE=1/1000
START=512015
END=616339
TITLE=Chapter 3. News from the Plain

[CHAPTER]
TIMEBASE=1/1000
START=616339
END=778061
TITLE=Chapter 4. Shadows Sleeping

[CHAPTER]
TIMEBASE=1/1000
START=778061
END=1008647
TITLE=Chapter 5. Nightmares Walking

[CHAPTER]
TIMEBASE=1/1000
START=1008647
END=1156610
TITLE=Chapter 6. The Hunt Begins

[CHAPTER]
TIMEBASE=1/1000
START=1156610
END=1222374
TITLE=Chapter 7. The Way Out of the Mountains

[CHAPTER]
TIMEBASE=1/1000
START=1222374
END=1411023
TITLE=Chapter 8. Jarra

[CHAPTER]
TIMEBASE=1/1000
START=1411023
END=1571273
TITLE=Chapter 9. Wolf Dreams

[CHAPTER]
TIMEBASE=1/1000
START=1571273
END=1747457
TITLE=Chapter 10. Secrets

[CHAPTER]
TIMEBASE=1/1000
START=1747457
END=1862296
TITLE=Chapter 11. Tar Valon

[CHAPTER]
TIMEBASE=1/1000
START=1862296
END=1969126
TITLE=Chapter 12. The Amyrlin Seat

[CHAPTER]
TIMEBASE=1/1000
START=1969126
END=2113521
TITLE=Chapter 13. Punishments

[CHAPTER]
TIMEBASE=1/1000
START=2113521
END=2240601
TITLE=Chapter 14. The Bite of the Thorns

[CHAPTER]
TIMEBASE=1/1000
START=2240601
END=2347109
TITLE=Chapter 15. The Gray Man

[CHAPTER]
TIMEBASE=1/1000
START=2347109
END=2431765
TITLE=Chapter 16. Hunters Three

[CHAPTER]
TIMEBASE=1/1000
START=2431765
END=2493759
TITLE=Chapter 17. The Red Sister

[CHAPTER]
TIMEBASE=1/1000
START=2493759
END=2595173
TITLE=Chapter 18. Healing

[CHAPTER]
TIMEBASE=1/1000
START=2595173
END=2677313
TITLE=Chapter 19. Awakening

[CHAPTER]
TIMEBASE=1/1000
START=2677313
END=2855593
TITLE=Chapter 20. Visitations

[CHAPTER]
TIMEBASE=1/1000
START=2855593
END=3021253
TITLE=Chapter 21. A World of Dreams

[CHAPTER]
TIMEBASE=1/1000
START=3021253
END=3327082
TITLE=Chapter 22. The Price of the Ring

[CHAPTER]
TIMEBASE=1/1000
START=3327082
END=3493419
TITLE=Chapter 23. Sealed

[CHAPTER]
TIMEBASE=1/1000
START=3493419
END=3659059
TITLE=Chapter 24. Scouting and Discoveries

[CHAPTER]
TIMEBASE=1/1000
START=3659059
END=3912915
TITLE=Chapter 25. Questions

[CHAPTER]
TIMEBASE=1/1000
START=3912915
END=4024090
TITLE=Chapter 26. Behind a Lock

[CHAPTER]
TIMEBASE=1/1000
START=4024090
END=4236910
TITLE=Chapter 27. Tel'aran'rhoid

[CHAPTER]
TIMEBASE=1/1000
START=4236910
END=4317511
TITLE=Chapter 28. A Way Out

[CHAPTER]
TIMEBASE=1/1000
START=4317511
END=4533801
TITLE=Chapter 29. A Trap to Spring

[CHAPTER]
TIMEBASE=1/1000
START=4533801
END=4767393
TITLE=Chapter 30. The First Toss

[CHAPTER]
TIMEBASE=1/1000
START=4767393
END=4900604
TITLE=Chapter 31. The Woman of Tanchico

[CHAPTER]
TIMEBASE=1/1000
START=4900604
END=5160146
TITLE=Chapter 32. The First Ship

[CHAPTER]
TIMEBASE=1/1000
START=5160146
END=5354357
TITLE=Chapter 33. Within the Weave

[CHAPTER]
TIMEBASE=1/1000
START=5354357
END=5522243
TITLE=Chapter 34. A Different Dance

[CHAPTER]
TIMEBASE=1/1000
START=5522243
END=5655760
TITLE=Chapter 35. The Falcon

[CHAPTER]
TIMEBASE=1/1000
START=5655760
END=5874861
TITLE=Chapter 36. Daughter of the Night

[CHAPTER]
TIMEBASE=1/1000
START=5874861
END=6030606
TITLE=Chapter 37. Fires in Cairhien

[CHAPTER]
TIMEBASE=1/1000
START=6030606
END=6550046
TITLE=Chapter 38. Maidens of the Spear

[CHAPTER]
TIMEBASE=1/1000
START=6550046
END=6907885
TITLE=Chapter 39. Threads in the Pattern

[CHAPTER]
TIMEBASE=1/1000
START=6907885
END=7070493
TITLE=Chapter 40. A Hero in the Night

[CHAPTER]
TIMEBASE=1/1000
START=7070493
END=7213861
TITLE=Chapter 41. A Hunter's Oath

[CHAPTER]
TIMEBASE=1/1000
START=7213861
END=7357824
TITLE=Chapter 42. Easing the Badger

[CHAPTER]
TIMEBASE=1/1000
START=7357824
END=7477831
TITLE=Chapter 43. Shadowbrothers

[CHAPTER]
TIMEBASE=1/1000
START=7477831
END=7670015
TITLE=Chapter 44. Hunted

[CHAPTER]
TIMEBASE=1/1000
START=7670015
END=7780270
TITLE=Chapter 45. Caemlyn

[CHAPTER]
TIMEBASE=1/1000
START=7780270
END=7899550
TITLE=Chapter 46. A Message Out of the Shadow

[CHAPTER]
TIMEBASE=1/1000
START=7899550
END=8010710
TITLE=Chapter 47. To Race the Shadow

[CHAPTER]
TIMEBASE=1/1000
START=8010710
END=8198114
TITLE=Chapter 48. Following the Craft

[CHAPTER]
TIMEBASE=1/1000
START=8198114
END=8462957
TITLE=Chapter 49. A Storm in Tear

[CHAPTER]
TIMEBASE=1/1000
START=8462957
END=8656902
TITLE=Chapter 50. The Hammer

[CHAPTER]
TIMEBASE=1/1000
START=8656902
END=8780395
TITLE=Chapter 51. Bait for the Net

[CHAPTER]
TIMEBASE=1/1000
START=8780395
END=8895688
TITLE=Chapter 52. In Search of a Remedy

[CHAPTER]
TIMEBASE=1/1000
START=8895688
END=9038848
TITLE=Chapter 53. A Flow of the Spirit

[CHAPTER]
TIMEBASE=1/1000
START=9038848
END=9340721
TITLE=Chapter 54. Into the Stone

[CHAPTER]
TIMEBASE=1/1000
START=9340721
END=9799626
TITLE=Chapter 55. What Is Written in Prophecy

[CHAPTER]
TIMEBASE=1/1000
START=9799626
END=10034500
TITLE=Chapter 56. People of the Dragon
