;FFMETADATA1
TITLE=04. The Shadow Rising
ARTIST=Robert Jordan
ALBUM=The Wheel of Time
GENRE=Audiobook

[CHAPTER]
TIMEBASE=1/1000
START=0
END=709301
TITLE=Chapter 1. Seeds of Shadow

[CHAPTER]
TIMEBASE=1/1000
START=709301
END=1158658
TITLE=Chapter 2. Whirlpools in the Pattern

[CHAPTER]
TIMEBASE=1/1000
START=1158658
END=1395121
TITLE=Chapter 3. Reflection

[CHAPTER]
TIMEBASE=1/1000
START=1395121
END=1566419
TITLE=Chapter 4. Strings

[CHAPTER]
TIMEBASE=1/1000
START=1566419
END=1726930
TITLE=Chapter 5. Questioners

[CHAPTER]
TIMEBASE=1/1000
START=1726930
END=2000791
TITLE=Chapter 6. Doorways

[CHAPTER]
TIMEBASE=1/1000
START=2000791
END=2261085
TITLE=Chapter 7. Playing With Fire

[CHAPTER]
TIMEBASE=1/1000
START=2261085
END=2499429
TITLE=Chapter 8. Hard Heads

[CHAPTER]
TIMEBASE=1/1000
START=2499429
END=2813953
TITLE=Chapter 9. Decisions

[CHAPTER]
TIMEBASE=1/1000
START=2813953
END=3188503
TITLE=Chapter 10. The Stone Stands

[CHAPTER]
TIMEBASE=1/1000
START=3188503
END=3460373
TITLE=Chapter 11. What Lies Hidden

[CHAPTER]
TIMEBASE=1/1000
START=3460373
END=3639984
TITLE=Chapter 12. Tanchico or the Tower

[CHAPTER]
TIMEBASE=1/1000
START=3639984
END=3801543
TITLE=Chapter 13. Rumors

[CHAPTER]
TIMEBASE=1/1000
START=3801543
END=3977392
TITLE=Chapter 14. Customs of Mayene

[CHAPTER]
TIMEBASE=1/1000
START=3977392
END=4256345
TITLE=Chapter 15. Into the Doorway

[CHAPTER]
TIMEBASE=1/1000
START=4256345
END=4462606
TITLE=Chapter 16. Leavetakings

[CHAPTER]
TIMEBASE=1/1000
START=4462606
END=4825333
TITLE=Chapter 17. Deceptions

[CHAPTER]
TIMEBASE=1/1000
START=4825333
END=4927602
TITLE=Chapter 18. Into the Ways

[CHAPTER]
TIMEBASE=1/1000
START=4927602
END=5119123
TITLE=Chapter 19. The Wavedancer

[CHAPTER]
TIMEBASE=1/1000
START=5119123
END=5384318
TITLE=Chapter 20. Winds Rising

[CHAPTER]
TIMEBASE=1/1000
START=5384318
END=5701895
TITLE=Chapter 21. Into the Heart

[CHAPTER]
TIMEBASE=1/1000
START=5701895
END=5919963
TITLE=Chapter 22. Out of the Stone

[CHAPTER]
TIMEBASE=1/1000
START=5919963
END=6356768
TITLE=Chapter 23. Beyond the Stone

[CHAPTER]
TIMEBASE=1/1000
START=6356768
END=6587078
TITLE=Chapter 24. Rhuidean

[CHAPTER]
TIMEBASE=1/1000
START=6587078
END=7256040
TITLE=Chapter 25. The Road to the Spear

[CHAPTER]
TIMEBASE=1/1000
START=7256040
END=8049020
TITLE=Chapter 26. The Dedicated

[CHAPTER]
TIMEBASE=1/1000
START=8049020
END=8168210
TITLE=Chapter 27. Within the Ways

[CHAPTER]
TIMEBASE=1/1000
START=8168210
END=8367620
TITLE=Chapter 28. To the Tower of Ghenjei

[CHAPTER]
TIMEBASE=1/1000
START=8367620
END=8540926
TITLE=Chapter 29. Homecoming

[CHAPTER]
TIMEBASE=1/1000
START=8540926
END=8660533
TITLE=Chapter 30. Beyond the Oak

[CHAPTER]
TIMEBASE=1/1000
START=8660533
END=9083902
TITLE=Chapter 31. Assurances

[CHAPTER]
TIMEBASE=1/1000
START=9083902
END=9294790
TITLE=Chapter 32. Questions to Be Asked

[CHAPTER]
TIMEBASE=1/1000
START=9294790
END=9656482
TITLE=Chapter 33. A New Weave in the Pattern

[CHAPTER]
TIMEBASE=1/1000
START=9656482
END=10005740
TITLE=Chapter 34. He Who Comes With the Dawn

[CHAPTER]
TIMEBASE=1/1000
START=10005740
END=10160089
TITLE=Chapter 35. Sharp Lessons

[CHAPTER]
TIMEBASE=1/1000
START=10160089
END=10349320
TITLE=Chapter 36. Misdirections

[CHAPTER]
TIMEBASE=1/1000
START=10349320
END=10651968
TITLE=Chapter 37. Imre Stand

[CHAPTER]
TIMEBASE=1/1000
START=10651968
END=10890893
TITLE=Chapter 38. Hidden Faces

[CHAPTER]
TIMEBASE=1/1000
START=10890893
END=11108674
TITLE=Chapter 39. A Cup of Wine

[CHAPTER]
TIMEBASE=1/1000
START=11108674
END=11200600
TITLE=Chapter 40. Hunter of Trollocs

[CHAPTER]
TIMEBASE=1/1000
START=11200600
END=11324260
TITLE=Chapter 41. Among the Tuatha'an

[CHAPTER]
TIMEBASE=1/1000
START=11324260
END=11454193
TITLE=Chapter 42. A Missing Leaf

[CHAPTER]
TIMEBASE=1/1000
START=11454193
END=11524903
TITLE=Chapter 43. Care for the Living

[CHAPTER]
TIMEBASE=1/1000
START=11524903
END=11643981
TITLE=Chapter 44. The Breaking Storm

[CHAPTER]
TIMEBASE=1/1000
START=11643981
END=11844001
TITLE=Chapter 45. The Tinker's Sword

[CHAPTER]
TIMEBASE=1/1000
START=11844001
END=12019497
TITLE=Chapter 46. Veils

[CHAPTER]
TIMEBASE=1/1000
START=12019497
END=12238701
TITLE=Chapter 47. The Truth of a Viewing

[CHAPTER]
TIMEBASE=1/1000
START=12238701
END=12354386
TITLE=Chapter 48. An Offer Refused

[CHAPTER]
TIMEBASE=1/1000
START=12354386
END=12492803
TITLE=Chapter 49. Cold Rocks Hold

[CHAPTER]
TIMEBASE=1/1000
START=12492803
END=12725778
TITLE=Chapter 50. Traps

[CHAPTER]
TIMEBASE=1/1000
START=12725778
END=12856610
TITLE=Chapter 51. Revelations in Tanchico

[CHAPTER]
TIMEBASE=1/1000
START=12856610
END=13058834
TITLE=Chapter 52. Need

[CHAPTER]
TIMEBASE=1/1000
START=13058834
END=13232898
TITLE=Chapter 53. The Price of a Departure

[CHAPTER]
TIMEBASE=1/1000
START=13232898
END=13388129
TITLE=Chapter 54. Into the Palace

[CHAPTER]
TIMEBASE=1/1000
START=13388129
END=13475341
TITLE=Chapter 55. Into the Deep

[CHAPTER]
TIMEBASE=1/1000
START=13475341
END=13649310
TITLE=Chapter 56. Goldeneyes

[CHAPTER]
TIMEBASE=1/1000
START=13649310
END=13837828
TITLE=Chapter 57. A Breaking in the Three-fold Land

[CHAPTER]
TIMEBASE=1/1000
START=13837828
END=13981500
TITLE=Chapter 58. The Traps of Rhuidean
