;FFMETADATA1
TITLE=05. The Fires of Heaven
ARTIST=Robert Jordan
ALBUM=The Wheel of Time
GENRE=Audiobook

[CHAPTER]
TIMEBASE=1/1000
START=0
END=154118
TITLE=Chapter 0. The First Sparks Fall

[CHAPTER]
TIMEBASE=1/1000
START=154118
END=287368
TITLE=Chapter 1. Fanning the Sparks

[CHAPTER]
TIMEBASE=1/1000
START=287368
END=386617
TITLE=Chapter 2. Rhuidean

[CHAPTER]
TIMEBASE=1/1000
START=386617
END=518788
TITLE=Chapter 3. Pale Shadows

[CHAPTER]
TIMEBASE=1/1000
START=518788
END=622385
TITLE=Chapter 4. Twilight

[CHAPTER]
TIMEBASE=1/1000
START=622385
END=714462
TITLE=Chapter 5. Among the Wise Ones

[CHAPTER]
TIMEBASE=1/1000
START=714462
END=902681
TITLE=Chapter 6. Gateways

[CHAPTER]
TIMEBASE=1/1000
START=902681
END=970921
TITLE=Chapter 7. A Departure

[CHAPTER]
TIMEBASE=1/1000
START=970921
END=1043863
TITLE=Chapter 8. Over the Border

[CHAPTER]
TIMEBASE=1/1000
START=1043863
END=1149796
TITLE=Chapter 9. A Signal

[CHAPTER]
TIMEBASE=1/1000
START=1149796
END=1296394
TITLE=Chapter 10. Figs and Mice

[CHAPTER]
TIMEBASE=1/1000
START=1296394
END=1372661
TITLE=Chapter 11. The Nine Horse Hitch

[CHAPTER]
TIMEBASE=1/1000
START=1372661
END=1405654
TITLE=Chapter 12. An Old Pipe

[CHAPTER]
TIMEBASE=1/1000
START=1405654
END=1487142
TITLE=Chapter 13. A Small Room in Sienda

[CHAPTER]
TIMEBASE=1/1000
START=1487142
END=1588999
TITLE=Chapter 14. Meetings

[CHAPTER]
TIMEBASE=1/1000
START=1588999
END=1791840
TITLE=Chapter 15. What Can Be Learned in Dreams

[CHAPTER]
TIMEBASE=1/1000
START=1791840
END=1868863
TITLE=Chapter 16. An Unexpected Offer

[CHAPTER]
TIMEBASE=1/1000
START=1868863
END=1975744
TITLE=Chapter 17. Heading West

[CHAPTER]
TIMEBASE=1/1000
START=1975744
END=2063479
TITLE=Chapter 18. A Hound of Darkness

[CHAPTER]
TIMEBASE=1/1000
START=2063479
END=2123108
TITLE=Chapter 19. Memories

[CHAPTER]
TIMEBASE=1/1000
START=2123108
END=2187311
TITLE=Chapter 20. Jangai Pass

[CHAPTER]
TIMEBASE=1/1000
START=2187311
END=2283917
TITLE=Chapter 21. The Gift of a Blade

[CHAPTER]
TIMEBASE=1/1000
START=2283917
END=2411979
TITLE=Chapter 22. Birdcalls by Night

[CHAPTER]
TIMEBASE=1/1000
START=2411979
END=2486697
TITLE=Chapter 23. "The Fifth, I Give You"

[CHAPTER]
TIMEBASE=1/1000
START=2486697
END=2557923
TITLE=Chapter 24. A Message Sent

[CHAPTER]
TIMEBASE=1/1000
START=2557923
END=2660927
TITLE=Chapter 25. Dreams of Galad

[CHAPTER]
TIMEBASE=1/1000
START=2660927
END=2751072
TITLE=Chapter 26. Sallie Daera

[CHAPTER]
TIMEBASE=1/1000
START=2751072
END=2909065
TITLE=Chapter 27. The Practice of Diffidence

[CHAPTER]
TIMEBASE=1/1000
START=2909065
END=3031781
TITLE=Chapter 28. Trapped

[CHAPTER]
TIMEBASE=1/1000
START=3031781
END=3106365
TITLE=Chapter 29. Memories of Saldaea

[CHAPTER]
TIMEBASE=1/1000
START=3106365
END=3177705
TITLE=Chapter 30. A Wager

[CHAPTER]
TIMEBASE=1/1000
START=3177705
END=3291333
TITLE=Chapter 31. The Far Snows

[CHAPTER]
TIMEBASE=1/1000
START=3291333
END=3391076
TITLE=Chapter 32. A Short Spear

[CHAPTER]
TIMEBASE=1/1000
START=3391076
END=3488925
TITLE=Chapter 33. A Question of Crimson

[CHAPTER]
TIMEBASE=1/1000
START=3488925
END=3615977
TITLE=Chapter 34. A Silver Arrow

[CHAPTER]
TIMEBASE=1/1000
START=3615977
END=3689027
TITLE=Chapter 35. Ripped Away

[CHAPTER]
TIMEBASE=1/1000
START=3689027
END=3813853
TITLE=Chapter 36. A New Name

[CHAPTER]
TIMEBASE=1/1000
START=3813853
END=3907001
TITLE=Chapter 37. Performances in Samara

[CHAPTER]
TIMEBASE=1/1000
START=3907001
END=3952846
TITLE=Chapter 38. An Old Acquaintance

[CHAPTER]
TIMEBASE=1/1000
START=3952846
END=4034435
TITLE=Chapter 39. Encounters in Samara

[CHAPTER]
TIMEBASE=1/1000
START=4034435
END=4132420
TITLE=Chapter 40. The Wheel Weaves

[CHAPTER]
TIMEBASE=1/1000
START=4132420
END=4211186
TITLE=Chapter 41. The Craft of Kin Tovere

[CHAPTER]
TIMEBASE=1/1000
START=4211186
END=4325090
TITLE=Chapter 42. Before the Arrow

[CHAPTER]
TIMEBASE=1/1000
START=4325090
END=4481077
TITLE=Chapter 43. This Place, This Day

[CHAPTER]
TIMEBASE=1/1000
START=4481077
END=4659141
TITLE=Chapter 44. The Lesser Sadness

[CHAPTER]
TIMEBASE=1/1000
START=4659141
END=4745932
TITLE=Chapter 45. After the Storm

[CHAPTER]
TIMEBASE=1/1000
START=4745932
END=4850041
TITLE=Chapter 46. Other Battles, Other Weapons

[CHAPTER]
TIMEBASE=1/1000
START=4850041
END=5004929
TITLE=Chapter 47. The Price of a Ship

[CHAPTER]
TIMEBASE=1/1000
START=5004929
END=5114955
TITLE=Chapter 48. Leavetakings

[CHAPTER]
TIMEBASE=1/1000
START=5114955
END=5261934
TITLE=Chapter 49. To Boannda

[CHAPTER]
TIMEBASE=1/1000
START=5261934
END=5430573
TITLE=Chapter 50. To Teach, and Learn

[CHAPTER]
TIMEBASE=1/1000
START=5430573
END=5612453
TITLE=Chapter 51. News Comes to Cairhien

[CHAPTER]
TIMEBASE=1/1000
START=5612453
END=5807693
TITLE=Chapter 52. Choices

[CHAPTER]
TIMEBASE=1/1000
START=5807693
END=5949533
TITLE=Chapter 53. Fading Words

[CHAPTER]
TIMEBASE=1/1000
START=5949533
END=6162748
TITLE=Chapter 54. To Caemlyn

[CHAPTER]
TIMEBASE=1/1000
START=6162748
END=6469096
TITLE=Chapter 55. The Threads Burn

[CHAPTER]
TIMEBASE=1/1000
START=6469096
END=6577500
TITLE=Chapter 56. Glowing Embers
