;FFMETADATA1
TITLE=06. Lord of Chaos
ARTIST=Robert Jordan
ALBUM=The Wheel of Time
GENRE=Audiobook

[CHAPTER]
TIMEBASE=1/1000
START=0
END=467795
TITLE=Chapter 0. Lord of Chaos/Prologue

[CHAPTER]
TIMEBASE=1/1000
START=467795
END=619928
TITLE=Chapter 1. Lion on the Hill

[CHAPTER]
TIMEBASE=1/1000
START=619928
END=619928
TITLE=Chapter 2. A New Arrival

[CHAPTER]
TIMEBASE=1/1000
START=619928
END=787378
TITLE=Chapter 3. Lord of Chaos/Chapter 3

[CHAPTER]
TIMEBASE=1/1000
START=787378
END=934130
TITLE=Chapter 4. A Sense of Humor

[CHAPTER]
TIMEBASE=1/1000
START=934130
END=1050030
TITLE=Chapter 5. A Different Dance

[CHAPTER]
TIMEBASE=1/1000
START=1050030
END=1171612
TITLE=Chapter 6. Threads Woven of Shadow

[CHAPTER]
TIMEBASE=1/1000
START=1171612
END=1251423
TITLE=Chapter 7. A Matter of Thought

[CHAPTER]
TIMEBASE=1/1000
START=1251423
END=1340324
TITLE=Chapter 8. The Storm Gathers

[CHAPTER]
TIMEBASE=1/1000
START=1340324
END=1431200
TITLE=Chapter 9. Plans

[CHAPTER]
TIMEBASE=1/1000
START=1431200
END=1513118
TITLE=Chapter 10. A Saying in the Borderlands

[CHAPTER]
TIMEBASE=1/1000
START=1513118
END=1638422
TITLE=Chapter 11. Lessons and Teachers

[CHAPTER]
TIMEBASE=1/1000
START=1638422
END=1771315
TITLE=Chapter 12. Questions and Answers

[CHAPTER]
TIMEBASE=1/1000
START=1771315
END=1894716
TITLE=Chapter 13. Under the Dust

[CHAPTER]
TIMEBASE=1/1000
START=1894716
END=2110786
TITLE=Chapter 14. Dreams and Nightmares

[CHAPTER]
TIMEBASE=1/1000
START=2110786
END=2219726
TITLE=Chapter 15. A Pile of Sand

[CHAPTER]
TIMEBASE=1/1000
START=2219726
END=2458863
TITLE=Chapter 16. Tellings of the Wheel

[CHAPTER]
TIMEBASE=1/1000
START=2458863
END=2572834
TITLE=Chapter 17. The Wheel of a Life

[CHAPTER]
TIMEBASE=1/1000
START=2572834
END=2770916
TITLE=Chapter 18. A Taste of Solitude

[CHAPTER]
TIMEBASE=1/1000
START=2770916
END=2881765
TITLE=Chapter 19. Matters of Toh

[CHAPTER]
TIMEBASE=1/1000
START=2881765
END=2974764
TITLE=Chapter 20. From the Stedding

[CHAPTER]
TIMEBASE=1/1000
START=2974764
END=3029571
TITLE=Chapter 21. To Shadar Logoth

[CHAPTER]
TIMEBASE=1/1000
START=3029571
END=3094366
TITLE=Chapter 22. Heading South

[CHAPTER]
TIMEBASE=1/1000
START=3094366
END=3251094
TITLE=Chapter 23. To Understand a Message

[CHAPTER]
TIMEBASE=1/1000
START=3251094
END=3356332
TITLE=Chapter 24. An Embassy

[CHAPTER]
TIMEBASE=1/1000
START=3356332
END=3525785
TITLE=Chapter 25. Like Lightning and Rain

[CHAPTER]
TIMEBASE=1/1000
START=3525785
END=3700748
TITLE=Chapter 26. Connecting Lines

[CHAPTER]
TIMEBASE=1/1000
START=3700748
END=3790277
TITLE=Chapter 27. Gifts

[CHAPTER]
TIMEBASE=1/1000
START=3790277
END=4058934
TITLE=Chapter 28. Letters

[CHAPTER]
TIMEBASE=1/1000
START=4058934
END=4201849
TITLE=Chapter 29. Fire and Spirit

[CHAPTER]
TIMEBASE=1/1000
START=4201849
END=4407243
TITLE=Chapter 30. To Heal Again

[CHAPTER]
TIMEBASE=1/1000
START=4407243
END=4558479
TITLE=Chapter 31. Red Wax

[CHAPTER]
TIMEBASE=1/1000
START=4558479
END=4799671
TITLE=Chapter 32. Summoned in Haste

[CHAPTER]
TIMEBASE=1/1000
START=4799671
END=4896482
TITLE=Chapter 33. Courage to Strengthen

[CHAPTER]
TIMEBASE=1/1000
START=4896482
END=5018011
TITLE=Chapter 34. Journey to Salidar

[CHAPTER]
TIMEBASE=1/1000
START=5018011
END=5224704
TITLE=Chapter 35. In the Hall of the Sitters

[CHAPTER]
TIMEBASE=1/1000
START=5224704
END=5357229
TITLE=Chapter 36. The Amyrlin Is Raised

[CHAPTER]
TIMEBASE=1/1000
START=5357229
END=5418729
TITLE=Chapter 37. When Battle Begins

[CHAPTER]
TIMEBASE=1/1000
START=5418729
END=5519748
TITLE=Chapter 38. A Sudden Chill

[CHAPTER]
TIMEBASE=1/1000
START=5519748
END=5686693
TITLE=Chapter 39. Possibilities

[CHAPTER]
TIMEBASE=1/1000
START=5686693
END=5820705
TITLE=Chapter 40. Unexpected Laughter

[CHAPTER]
TIMEBASE=1/1000
START=5820705
END=5892491
TITLE=Chapter 41. A Threat

[CHAPTER]
TIMEBASE=1/1000
START=5892491
END=6058366
TITLE=Chapter 42. The Black Tower

[CHAPTER]
TIMEBASE=1/1000
START=6058366
END=6203973
TITLE=Chapter 43. The Crown of Roses

[CHAPTER]
TIMEBASE=1/1000
START=6203973
END=6445275
TITLE=Chapter 44. The Color of Trust

[CHAPTER]
TIMEBASE=1/1000
START=6445275
END=6550820
TITLE=Chapter 45. A Bitter Thought

[CHAPTER]
TIMEBASE=1/1000
START=6550820
END=6612657
TITLE=Chapter 46. Beyond the Gate

[CHAPTER]
TIMEBASE=1/1000
START=6612657
END=6822294
TITLE=Chapter 47. The Wandering Woman

[CHAPTER]
TIMEBASE=1/1000
START=6822294
END=6950476
TITLE=Chapter 48. Leaning on the Knife

[CHAPTER]
TIMEBASE=1/1000
START=6950476
END=7047819
TITLE=Chapter 49. The Mirror of Mists

[CHAPTER]
TIMEBASE=1/1000
START=7047819
END=7209780
TITLE=Chapter 50. Thorns

[CHAPTER]
TIMEBASE=1/1000
START=7209780
END=7418501
TITLE=Chapter 51. The Taking

[CHAPTER]
TIMEBASE=1/1000
START=7418501
END=7549240
TITLE=Chapter 52. Weaves of the Power

[CHAPTER]
TIMEBASE=1/1000
START=7549240
END=7549240
TITLE=Chapter 53. The Feast of Lights

[CHAPTER]
TIMEBASE=1/1000
START=7549240
END=7763637
TITLE=Chapter 54. The Sending

[CHAPTER]
TIMEBASE=1/1000
START=7763637
END=7892500
TITLE=Chapter 55. Lord of Chaos/Chapter 55
