;FFMETADATA1
TITLE=07. A Crown of Swords
ARTIST=Robert Jordan
ALBUM=The Wheel of Time
GENRE=Audiobook

[CHAPTER]
TIMEBASE=1/1000
START=0
END=326346
TITLE=Chapter 0. Lightnings

[CHAPTER]
TIMEBASE=1/1000
START=326346
END=399365
TITLE=Chapter 1. High Chasaline

[CHAPTER]
TIMEBASE=1/1000
START=399365
END=559486
TITLE=Chapter 2. The Butcher's Yard

[CHAPTER]
TIMEBASE=1/1000
START=559486
END=727728
TITLE=Chapter 3. Hill of the Golden Dawn

[CHAPTER]
TIMEBASE=1/1000
START=727728
END=859575
TITLE=Chapter 4. Into Cairhien

[CHAPTER]
TIMEBASE=1/1000
START=859575
END=1006485
TITLE=Chapter 5. A Broken Crown

[CHAPTER]
TIMEBASE=1/1000
START=1006485
END=1134743
TITLE=Chapter 6. Old Fear, and New Fear

[CHAPTER]
TIMEBASE=1/1000
START=1134743
END=1291002
TITLE=Chapter 7. Pitfalls and Tripwires

[CHAPTER]
TIMEBASE=1/1000
START=1291002
END=1357122
TITLE=Chapter 8. The Figurehead

[CHAPTER]
TIMEBASE=1/1000
START=1357122
END=1461629
TITLE=Chapter 9. A Pair of Silverpike

[CHAPTER]
TIMEBASE=1/1000
START=1461629
END=1577395
TITLE=Chapter 10. Unseen Eyes

[CHAPTER]
TIMEBASE=1/1000
START=1577395
END=1640278
TITLE=Chapter 11. An Oath

[CHAPTER]
TIMEBASE=1/1000
START=1640278
END=1855172
TITLE=Chapter 12. A Morning of Victory

[CHAPTER]
TIMEBASE=1/1000
START=1855172
END=1930649
TITLE=Chapter 14. White Plumes

[CHAPTER]
TIMEBASE=1/1000
START=1930649
END=1987082
TITLE=Chapter 15. Insects

[CHAPTER]
TIMEBASE=1/1000
START=1987082
END=2081128
TITLE=Chapter 16. A Touch on the Cheek

[CHAPTER]
TIMEBASE=1/1000
START=2081128
END=2195069
TITLE=Chapter 17. The Triumph of Logic

[CHAPTER]
TIMEBASE=1/1000
START=2195069
END=2454870
TITLE=Chapter 18. As the Plow Breaks the Earth

[CHAPTER]
TIMEBASE=1/1000
START=2454870
END=2530227
TITLE=Chapter 19. Diamonds and Stars

[CHAPTER]
TIMEBASE=1/1000
START=2530227
END=2616200
TITLE=Chapter 20. Patterns Within Patterns

[CHAPTER]
TIMEBASE=1/1000
START=2616200
END=2768410
TITLE=Chapter 21. Swovan Night

[CHAPTER]
TIMEBASE=1/1000
START=2768410
END=2885630
TITLE=Chapter 22. Small Sacrifices

[CHAPTER]
TIMEBASE=1/1000
START=2885630
END=2953740
TITLE=Chapter 23. Next Door to a Weaver

[CHAPTER]
TIMEBASE=1/1000
START=2953740
END=3029202
TITLE=Chapter 24. The Kin

[CHAPTER]
TIMEBASE=1/1000
START=3029202
END=3079352
TITLE=Chapter 25. Mindtrap

[CHAPTER]
TIMEBASE=1/1000
START=3079352
END=3163734
TITLE=Chapter 26. The Irrevocable Words

[CHAPTER]
TIMEBASE=1/1000
START=3163734
END=3287596
TITLE=Chapter 27. To Be Alone

[CHAPTER]
TIMEBASE=1/1000
START=3287596
END=3386455
TITLE=Chapter 28. Bread and Cheese

[CHAPTER]
TIMEBASE=1/1000
START=3386455
END=4044631
TITLE=Chapter 29. The Festival of Birds

[CHAPTER]
TIMEBASE=1/1000
START=4044631
END=4161533
TITLE=Chapter 30. The First Cup

[CHAPTER]
TIMEBASE=1/1000
START=4161533
END=4387106
TITLE=Chapter 31. Mashiara

[CHAPTER]
TIMEBASE=1/1000
START=4387106
END=4554845
TITLE=Chapter 32. Sealed to the Flame

[CHAPTER]
TIMEBASE=1/1000
START=4554845
END=4642423
TITLE=Chapter 33. A Bath

[CHAPTER]
TIMEBASE=1/1000
START=4642423
END=4778031
TITLE=Chapter 34. Ta'veren

[CHAPTER]
TIMEBASE=1/1000
START=4778031
END=4891375
TITLE=Chapter 35. Into the Woods

[CHAPTER]
TIMEBASE=1/1000
START=4891375
END=5050374
TITLE=Chapter 36. Blades

[CHAPTER]
TIMEBASE=1/1000
START=5050374
END=5122797
TITLE=Chapter 37. A Note from the Palace

[CHAPTER]
TIMEBASE=1/1000
START=5122797
END=5277351
TITLE=Chapter 38. Six Stories

[CHAPTER]
TIMEBASE=1/1000
START=5277351
END=5986064
TITLE=Chapter 39. Promises to Keep

[CHAPTER]
TIMEBASE=1/1000
START=5986064
END=6098079
TITLE=Chapter 40. Spears

[CHAPTER]
TIMEBASE=1/1000
START=6098079
END=6327500
TITLE=Chapter 41. A Crown of Swords
